#!/usr/bin/env bash
# This script gives you information about the holbertonschool file

hbs="bestschool"

if [ -e $bs ]
then
    echo "$bs file exists"

    if [ -s $hbs ]
    then
	echo "$bs file is not empty"
    else
	echo "$bs file is empty"
    fi

    if [ -f $bs ]
    then
	echo "$bs is a regular file"
    fi
else
    echo "$bs file does not exist"
fi
